name: Verify frontend

on:
  pull_request:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        env:
          NEXT_PUBLIC_API_URL: ""
        run: npm run build
